### ISSUE TITLE
Built data should be pushed to depot

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/starforge#10]
Just an issue for tracking purposes.

**Comment by natefoo** [comment]
@erasche, could you have jenkins place the outputs into subdirectories based on the thing being built? Some output names are not consistent such that i can use `fname.split('-')[0]`.

Actually, what's with the 32 bit linux, mac, and windows builds of tbl2asn (where did they come from)?

xref bgruening/galaxytools#102

**Comment by hexylena** [comment]
Okay, can do. Sorry about that.

Tbl2asn is prebuilt for us by NCBI, but without any version information. We
separate it into a set of versioned files.

**Comment by hexylena** [comment]
@natefoo okay, looked at the "Collect-for-depot" recipe, and here's what it's running:

```
find /var/lib/jenkins/workspace/Docker-Build/ -mindepth 2 -maxdepth 3 \
    -not -wholename '*git*' -and -not -name 'build.*' \
    -and -not -name '*.sh' -and -not -name '*.diff' \
    -and -not -name '*.patch' -and -not -name 'Dockerfile' \
    -type f -exec cp '{}' /opt/depot/data/ \;
```

This may not be a perfectly easy problem to solve unfortunately. Given the file listing, I think the easier option would be to just rename everything properly.

**Comment by hexylena** [comment]
Let me resolve the v2 issues first, and I'll name things proiperly as part of that (since most of the issues are in code that I wrote)

**Comment by hexylena** [comment]
v2 should be ready to go. https://github.com/galaxyproject/docker-build/pull/15#issuecomment-108973171 

This includes fixes for versions/names in all of the things I can fix, and I've removed GD-2.56.tar.gz as it also had a bad name, and is now available in https://github.com/bgruening/download_store/tree/master/GD-2.56

**Comment by natefoo** [comment]
Is there a reason not to simply grab `*/*.tar.gz` rather than exclude everything else? How about:

```
cd /var/lib/jenkins/workspace/Docker-Build && \
    for f in */*.tar.gz; do mkdir -p /opt/depot/data/`dirname $f` && cp $f /opt/depot/data/$f; done
```

**Comment by hexylena** [comment]
@natefoo there was a reason, but it's escaping me. Yeah, we'll switch to that. 

Also, fyi, the above would fail with v2 versioned directories. I'll work something out and keep them separated into folders for you.

**Comment by natefoo** [comment]
@erasche awesome.
