### ISSUE TITLE
manylinux1 and platform-specific capabilities conflict

### ISSUE THREAD

**Issue by natefoo** [galaxyproject/starforge#109]
We have a hack in place that allows us to install Starforge in our manylinux1 docker images because Starforge currently depends on a fork of wheel to build platform-specific wheels (which is unwanted for manylinux1 wheels).

Since we probably don't need to build platform-specific wheels going forward (but maybe should not drop support for them entirely), Starforge should support these concurrently. The changes in the wheel fork can be spun into a separate library to accomplish this.

**Comment by bgruening** [comment]
Am I wrong in the assumption that starforge is not using the latest starforge when creating PR? 

This commit is not included: https://github.com/galaxyproject/starforge/commit/0dbecb79e28baecb62546b629cae9dbebf46df19

**Comment by natefoo** [comment]
Probably true, the image build process on the build server right now is a manual process. =(

Let's get rid of the wheel fork so we can easily automate updating the build environment.

**Comment by natefoo** [comment]
One clarification - the `starforge/manylinux1*` images should include that commit. The pure python image may not.
