### ISSUE TITLE
Need R packages

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/starforge#11]
xref https://github.com/galaxyproject/tools-iuc/issues/101

**Comment by natefoo** [comment]
Ping @davebx

**Comment by bgruening** [comment]
@davebx can you please create a package for R 3.2. I need this for the new DESeq2 release: https://github.com/galaxyproject/tools-iuc/pull/20

**Comment by bgruening** [comment]
ping @davebx Do you have any other secrets in your recipe that you would like to share with us :)

**Comment by davebx** [comment]
@bgruening Absolutely, I've been meaning to publish the steps I use to generate a relocatable build of R, this seems like a good place to do it.

**Comment by bgruening** [comment]
@davebx  :beer:

Thanks!
