### ISSUE TITLE
Should we start versioning packages?

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/starforge#12]
E.g. we have an `emboss` folder which is specifically `6.6.0`? Thoughts? @bgruening @natefoo

**Comment by bgruening** [comment]
This really depends on how @natefoo will use it or couple it to the depot.
I think tags or branches are overkill, subdirectories are probably enough, something like `/emboss/6.6.0/`

**Comment by natefoo** [comment]
I like the simplicity of the versioned subdirectories.

Hopefully we won't have too many cases where we are concurrently maintaining multiple versions of things?

**Comment by bgruening** [comment]
This is also my secret hope, build once and forget about it forever ;)
