### ISSUE TITLE
Generate missing wheels

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/starforge#173]
I don't think we have wheels for most of these - I could be wrong though...

```
python-genomespaceclient==0.1.8
  - boto3 [required: Any, installed: 1.4.7]
    - botocore [required: <1.8.0,>=1.7.0, installed: 1.7.35]
      - docutils [required: >=0.10, installed: 0.12]
      - jmespath [required: <1.0.0,>=0.7.1, installed: 0.9.3]
      - python-dateutil [required: <3.0.0,>=2.1, installed: 2.6.1]
        - six [required: >=1.5, installed: 1.11.0]
    - jmespath [required: <1.0.0,>=0.7.1, installed: 0.9.3]
    - s3transfer [required: <0.2.0,>=0.1.10, installed: 0.1.11]
      - botocore [required: <2.0.0,>=1.3.0, installed: 1.7.35]
        - docutils [required: >=0.10, installed: 0.12]
        - jmespath [required: <1.0.0,>=0.7.1, installed: 0.9.3]
        - python-dateutil [required: <3.0.0,>=2.1, installed: 2.6.1]
          - six [required: >=1.5, installed: 1.11.0]
      - futures [required: <4.0.0,>=2.2.0, installed: 3.1.1]
  - python-swiftclient [required: Any, installed: 3.4.0]
    - futures [required: >=3.0, installed: 3.1.1]
    - requests [required: >=1.1, installed: 2.10.0]
    - six [required: >=1.5.2, installed: 1.11.0]
  - requests [required: Any, installed: 2.10.0]
```

**Comment by nsoranzo** [comment]
We can workaround this by increasing the Galaxy requirement to `python-genomespaceclient==0.2`, which already has a wheel on PyPI.

There are other 2 packages which don't have a wheel either on PyPI or generated by Starforge:
- docopt-0.6.2
- pycparser-2.18

**Comment by jmchilton** [comment]
@nsoranzo I've included a lot of these in https://github.com/galaxyproject/starforge/pull/177. docopt has already been added but was never copied - so looks like I messed up during the handling of https://github.com/galaxyproject/starforge/pull/110. I think it needs to be manually regenerated I guess and uploaded.

**Comment by nsoranzo** [comment]
docopt 0.6.2 fixed in https://github.com/galaxyproject/starforge/pull/194

**Comment by nsoranzo** [comment]
New wheels should be added to https://github.com/galaxyproject/starforge-recipes/
