### ISSUE TITLE
Fix mercurial and pysam sources on wheels.galaxyproject.org

### ISSUE THREAD

**Issue by natefoo** [galaxyproject/starforge#180]
The sdists for both mercurial 3.5 and 3.7.3 and pysam 0.8.* are invalid and should be replaced. Mercurial with the upstream tarballs and pysam with the source tarballs in Github specified in wheels.yml, with the corresponding prebuild changes applied.

**Comment by natefoo** [comment]
This is done. The full list of replaced sdists is:

- bz2file-0.98.tar.gz
- docutils-0.12.tar.gz
- Markdown-2.6.3.tar.gz
- mercurial-3.5.tar.gz
- mercurial-3.7.3.tar.gz
- ordereddict-1.1.tar.gz
- Parsley-1.3.tar.gz
- pysam-0.8.3+gx1.tar.gz
- pysam-0.8.4+gx1.tar.gz
- pysam-0.8.4+gx5.tar.gz
- wchartype-0.1.tar.gz

The others had invalid `setup.py`s due to #181.

For pysam, because part of the prebuild changes are to install cython, I have added `'install_requires': ['cython>=0.21<0.23']` to the `setup()` function to the source tarballs. That makes them unsuitable for use in building wheels, since it would also pass the cython dependency on to the wheel. Cython is a build dependency but not an install dependency, but the existing (pre PEP-518) method for specifying build dependencies is setuptools' `setup_requires()`, which uses `easy_install` and doesn't work so great in the pip context. If you want to build wheels from the pysam sdists, remove `install_requires` from `setup.py` or use the upstream version and make the prebuild changes as specified in wheels.yml.

**Comment by natefoo** [comment]
As a result, you can now perform the following successfully:

```sh-session
$ pip install --index-url https://wheels.galaxyproject.org/simple/ \ 
    --extra-index-url https://pypi.python.org/simple/ -r requirements.txt --no-binary :all:
```

This is handy for things like using a pydebug-enabled python on macOS, since there are many invalid macOS wheels in PyPI that specify a `none` SOABI tag that should really be `cp27m`, meaning they will not work with a `cp27dm` pydebug build.

Or if you're trying to port Galaxy to a new architecture...

**Comment by nsoranzo** [comment]
What about:
- biopython 1.66
- psycopg2 2.6.1
- pycrypto 2.6.1
- python_lzo 1.8
- PyYAML 3.11

? They also have `insert_setuptools: true` in `wheels/build/wheels.yml` .

**Comment by natefoo** [comment]
Their sdists on wheels.galaxyproject.org must be from upstream, I checked
all of *.tar.gz's setup.pys and they didn't hit.
