### ISSUE TITLE
Handle wheels that are purepy on some platforms and platform-specific on others

### ISSUE THREAD

**Issue by natefoo** [galaxyproject/starforge#184]
For example, watchdog is pure python on Linux but platform on macOS.

We could in theory add it to both sections, and restrict the platform entry to just the `macos-wheel` image set. This won't work currently because the purepy/platform dicts are collapsed to a single OrderedDict in [the config code](https://github.com/galaxyproject/starforge/blob/e5a486c88f6c29115d8652894ff77a3a82ac4bec/starforge/config/wheels.py#L63).

We could also try to collapse the purepy/python dicts to one and just add a `purepy` key to the wheel entries (defaults to `true`) that can either take a boolean or a hash with items `<key>: <bool>` where `<key>` is an imageset, image, or platform? Not sure which makes the most sense. Probably imageset.

**Comment by nsoranzo** [comment]
Looks like this was fixed: https://wheels.galaxyproject.org/simple/watchdog/

**Comment by natefoo** [comment]
I'm not sure if I was thinking my changes would fix it at the time, but the implementation of type guessing using `starforge wheel_type` makes this work (automatically!). Neat!
