### ISSUE TITLE
replace the removed pip -d option

### ISSUE THREAD

**Issue by martenson** [galaxyproject/starforge#200]
all builds will now error, xref https://github.com/galaxyproject/starforge/pull/197

we should be using [`pip download`](https://pip.pypa.io/en/stable/reference/pip_download/) instead

error: https://jenkins.galaxyproject.org/job/starforge-wheels/312/console

announced: https://pip.pypa.io/en/stable/news/

**Comment by martenson** [comment]
ping @natefoo

**Comment by natefoo** [comment]
Fixed in c516bae4052d326034c07d10ca0a639e7c393830, released in 0.3.6
