### ISSUE TITLE
Getting UCSC tools into the depot

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/starforge#21]
@natefoo can we get the UCSC binaries into the depot? We need them for a data manger and some converters.

**Comment by natefoo** [comment]
@bgruening okay, done. Completely untested, I just did a `./build` and `scp`... =)

**Comment by bgruening** [comment]
@natefoo this is how it should work. As less work as possible for you. Let's see!

@blankenberg do you have any thoughts on _one package for all UCSC tools_ vs.  _X separate packages_?

**Comment by blankenberg** [comment]
I'm ok with either, since they all just build at once a single package certainly makes sense.

**Comment by bgruening** [comment]
Great also my preferred solution! I will create/update such a package.

**Comment by blankenberg** [comment]
Best to just make sure it only includes the commercially usable stuff (src/lib, src/inc and src/utils and python directories): 
This directory contains the entire source tree for the
UCSC Genome Bioinformatics Group's suite of biological analysis 
and web display programs as well as some of Jim Kent's own tools.  
All files are copyrighted, but license is hereby granted for personal, 
academic, and non-profit use.  A license is also granted for the contents 
of the src/lib, src/inc and src/utils and python directories for commercial 
users.

**Comment by blankenberg** [comment]
@bgruening Thanks! :)

**Comment by hexylena** [comment]
@blankenberg we should be good on licensing issues.

@bgruening maybe this would be a good time to try out @jmchilton's planemo's ability to decompose tools into separate repositories? I feel like a single repo would be nice from a dev perspective, but end-users only need a couple of the tools for a basic galaxy installation (e.g. faToTwoBit for trackster) and shouldn't need to install the full complement of UCSC tools?

**Comment by bgruening** [comment]
@erasche it's about tool dependencies here, I'm not aware of a feature that can decompose tool_dependencies. Moreover, if you depend on a lot of UCSC tools you need to write a lot of code. It's < 150MB if we take all binaries. Is this too much?

**Comment by hexylena** [comment]
@bgruening ah, of course, I was thinking about tools...no 150 doesn't seem like a lot

**Comment by hexylena** [comment]
@bgruening you're writing up wrappers for them right? Something that'll make it to tools-iuc eventually? If not, let me know, and I can work/help on wrapping them as well.

**Comment by bgruening** [comment]
@erasche yes if time permits and on urgent demand ;)
@blankenberg also needs this for a data manager. So things coming together.

See here: https://github.com/bgruening/galaxytools/pull/129
I'm not sure about the repository thought. Imho these are more converters and should be attached to datatypes ...

**Comment by hexylena** [comment]
@bgruening hmm, good point. Many of them are just datatype converters. Ugh. Maybe we wait, pending that IUC datatype meeting?

**Comment by bgruening** [comment]
Exactly :)

**Comment by bgruening** [comment]
Initial version is now available and I have seen an increased usage :).
Thanks!
