### ISSUE TITLE
package_bowtie_2_2_4 Executable Permissions - can't run bowtie as non-galaxy user

### ISSUE THREAD

**Issue by dtrudg** [galaxyproject/starforge#25]
Installed bowtie2 from the toolshed, which brings in package_bowtie_2_2_4, which downloads bowtie binaries from depot.galaxyproject.org

http://depot.galaxyproject.org/package/linux/x86_64/bowtie2/bowtie2-2.2.4-linux-x86_64.tgz

Jobs submitted on our setup, running as a ‘real user’ (not galaxy user) via pulsar + SLURM fail with a permissions error. This is due to the permissions on some of the bowtie executables in the .tar.gz from depot being owner/group executable only. Other users cannot run bowtie2:

-rwxrwx---. 1 galaxy galaxy  18K Oct 22  2014 bowtie2

If I download the tar.gz from depot manually and extract then I get:

-rwxrwx--- 1 dtrudgian biohpc_admin  18K Oct 22  2014 bowtie2

Could the .tar.gz be fixed, so that the executables will work in a run as real user configuration? Is there any sensible way Galaxy could enforce permissions to guard against this issue?

**Comment by martenson** [comment]
I thought this was resolved by repacking the binary on depot with correct permissions. ping @davebx

**Comment by dtrudg** [comment]
If I go to:

http://depot.galaxyproject.org/package/linux/x86_64/bowtie2

... and do some manual downloads and extractions then:

2.2.4 has incorrect perms

``` sh
09:24 AM $ ls -lah bowtie2-2.2.4/bowtie2
-rwxr-x--- 1 dtrudg None 18K Oct 22  2014 bowtie2-2.2.4/bowtie2
```

2.1.0 has correct perms

``` sh
09:24 AM $ ls -lah bowtie2-2.1.0/bowtie2
-rwxr-xr-x 1 dtrudg None 15K Feb  5  2013 bowtie2-2.1.0/bowtie2
```

**Comment by davebx** [comment]
@dctrud I have corrected the permissions in the package on depot.

**Comment by dtrudg** [comment]
Looks good. Cheers! :beer:
