### ISSUE TITLE
Splitting build into different layers

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/starforge#3]
installing dependencies and downloading tarballs can take some time. It would be nice to have this as extra Docker layers so we do not need to repeat this during testing.
- apt-get extra layer
- download extra layer
- --no-cache switch for ./build to overwrite the layers

**Comment by natefoo** [comment]
+1, this is indeed a significant annoyance.

**Comment by hexylena** [comment]
I've got some work here that may help. https://github.com/erasche/docker-build I wasn't happy with the existing bash script/etc so I re-wrote it as python/yaml metadata file. 

A docker image is produced with "prebuild" stuff (apt-get/packages/commands) executed, and then the build.sh is run inside of that image. It's very much WIP. When I get it working with my stupid chado image (there are like 9000 bloody perl dependencies that have to be installed...caching was non-optional), then I'll re-write everything in this repo and PR.

**Comment by natefoo** [comment]
The scope, oh how it creeps.

But there are quite a few improvements that can be made, and I am equally unsatisfied with a collection of mostly duplicated shell scripts.
