### ISSUE TITLE
A Galactic Name

### ISSUE THREAD

**Issue by natefoo** [galaxyproject/starforge#33]
Since this is sorta useful, should we give it a Galactic name? Since it's about building things, the first things that popped into my head were:
- Stardust
- Nebula
- Starforge
- ??

**Comment by hexylena** [comment]
Stardust is cute :sparkles:

**Comment by martenson** [comment]
Polymerase :)

**Comment by hexylena** [comment]
If we're keepin with "galactic components which build things" maybe 'starforge'?

**Comment by nturaga** [comment]
Stardust is nice!

**Comment by martenson** [comment]
I like Starforge!

**Comment by hexylena** [comment]
:sparkles::hammer:

**Comment by jmchilton** [comment]
:+1::sparkles::hammer::smile::fireworks:

Also Nebula is [taken](https://github.com/kellrott/nebula).

**Comment by davebx** [comment]
Vague ideas:

Oort
Kuiper
Polaris
Cygnus
Echelon (might have some connotations for the ... conspiracy-conscious)
Mjölnir
конструктор (taken, sadly)
What's The Deal With This Gravitas Thing Anyway

@martenson Starforge is already [a thing](http://www.starforge.com/), if it matters.

**Comment by martenson** [comment]
everything is a thing :)

**Comment by hexylena** [comment]
[`r/shittymspaint`](https://www.reddit.com/r/shittymspaint) but I needed something to do over my lunch break

![please_dont_really_use_this](https://cloud.githubusercontent.com/assets/458683/10525562/0b009a78-734b-11e5-9680-2f8c93ebe0d0.png)

**Comment by natefoo** [comment]
Shiny!

**Comment by natefoo** [comment]
I think Starforge is the winner. All in favor? All opposed?

**Comment by martenson** [comment]
aye!

**Comment by martenson** [comment]
also @erasche that Thor's hammer producing sparkles while hitting magician's hat....that is next level.

**Comment by bgruening** [comment]
+1

**Comment by nturaga** [comment]
+1

**Comment by natefoo** [comment]
Done! Someone should update the README with our sweet logo.

**Comment by hexylena** [comment]
Oh please don't /actually/ use that... :fearful:

**Comment by davebx** [comment]
Or at least credit the artist if we do...

**Comment by natefoo** [comment]
:innocent: https://hub.docker.com/r/starforge/

**Comment by martenson** [comment]
rofl
