### ISSUE TITLE
A Galactic Logo

### ISSUE THREAD

**Issue by natefoo** [galaxyproject/starforge#41]
![starforge_logo](https://cloud.githubusercontent.com/assets/286969/11219713/0333a04e-8d2a-11e5-8058-368f627ed07f.png)

@erasche? =D

**Comment by martenson** [comment]
damn, I kinda like it

**Comment by natefoo** [comment]
Quick, let's make it official while he's off for the week! ;D

**Comment by martenson** [comment]
:+1:

**Comment by davebx** [comment]
:+1: x :100:

**Comment by hexylena** [comment]
**groan** haha. 

:+1: I love it @natefoo, the F is a nice touch.

**Comment by natefoo** [comment]
Added in f25758e02e9d7874e42bc9f1687a26da13ee3385
