### ISSUE TITLE
please rebuild nginx and upload to launchpad

### ISSUE THREAD

**Issue by rockpapergoat** [galaxyproject/starforge#78]
After the recent glibc CVE and updates, the nginx package fails to run, complaining about config that requires the upload module. Can you or someone affiliated with the project roll a new nginx package for distribution? The docker-galaxy container also relies on this version of nginx, so it's failing like so:

   unknown directive "upload_store" in /etc/nginx/nginx.conf:117

**Comment by mvdbeek** [comment]
Ongoing in PR #75 / @natefoo can you ping us once it's done ?

In the meantime you can install the old version like so:

```
apt-get remove nginx-common nginx-extras
apt-get install nginx-common=1.4.6-1ubuntu3.3ppa1 nginx-extras=1.4.6-1ubuntu3.3ppa1
```

**Comment by natefoo** [comment]
Sorry, I had the PR open in a tab for 2 weeks, just kept getting bumped down. Updated packages have been pushed to the PPA and are successfully built and published.

We need to get Jenkins building these (although there'd be no way to sign them?)

**Comment by mvdbeek** [comment]
Thanks @natefoo 
I'm not too familiar with building .debs ... when you do apt-get source $pkg, you automatically get those security fixes applied?

**Comment by hexylena** [comment]
@natefoo, no easy way to sign. I see a couple options.
1. Mint a new jenkins key, other groups do this. Use it to sign all galaxy stuff and keep it secure somewhere
2. Have a jenkins job for signing which emails you a .deb and then polls an email account for a reply from you with a signed deb? Or something.equally contrived ;)

**Comment by natefoo** [comment]
@mvdbeek Yes, apt-get source fetches the upstream source and the distro patches. When you do the debuild step, the patches are applied.

**Comment by natefoo** [comment]
@erasche We could have a general signing key and then add subkeys for Jenkins.

**Comment by rockpapergoat** [comment]
thanks, all. i didn't see that PR earlier. the pkg issue seems resolved for now.

**Comment by hexylena** [comment]
@natefoo I'd +1 a jenkins subkey.
